In [2]:
import numpy as np

# create a 2D array with shape (4, 4)
arr = np.array([[1, 2, 0, 4], [5, 6, 7, 8], [9, -10, 11, 12], [-5, -6, 7, 18],])

print(arr)

[[  1   2   0   4]
 [  5   6   7   8]
 [  9 -10  11  12]
 [ -5  -6   7  18]]


In [3]:
def normalize_matrix (matrix, do_norm = 0, bin_thresh = 0):
    mini = matrix.min()
    maxi = matrix.max()
    if do_norm == 0:
        print ('No normalization of structural connectivity matrix')
    elif do_norm == 1:
        print ('Binarization of structural matrix')
        if bin_thresh == 0:
            threshold = 0
        elif mini <= bin_thresh <= maxi:
            threshold = bin_thresh
        else:
            print('Threshold must be in values range. matrix minimum value > bin_thresh > matrix maxmimum value')
        matrix = matrix > 0

    elif do_norm == 2:
        print ('Normalization of structural matrix')
        matrix = matrix/maxi

    else:
        print('Specify normalization input. 0 = no normalization, 1 = binarize, 2 = normalize.')
    return matrix

In [4]:
M = normalize_matrix (arr, 1, 3)
print(M)

Binarization of structural matrix
[[ True  True False  True]
 [ True  True  True  True]
 [ True False  True  True]
 [False False  True  True]]
